name: flutter_advanced_course_multi_modular_clean_architecture
packages:
  # Include all modules in the workspace
  #  - 'core'
  #  - 'feature1'
  #  - 'feature2'
  # You can also use wildcards for flexibility, like:
  - core/**
  # - features/movies
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.3
      flutter: ">=1.17.0"
    dependencies:
      dio: 5.8.0+1

    dev_dependencies:
      build_runner: ^2.4.15
      flutter_lints: ^5.0.0


scripts:
#  bootstrap: melos bootstrap
  clean: melos clean
  update: flutter pub outdated
  upgrade: flutter pub upgrade --major-versions
  cleanAndBootstrap:
    run: melos run clean && melos bootstrap
  test:
    run: flutter test